### ISSUE TITLE
RSS/Atom feed

### ISSUE THREAD

**Issue by 1fexd** [strazzere/blog#1]
Would love to add your blog to my RSS reader, but it seems you don't have a feed set up - would you mind doing so? Seems like Hexo supports it via [hexo-generator-feed](https://github.com/hexojs/hexo-generator-feed)

Much appreciated!

**Comment by strazzere** [comment]
What is your website you want to use the RSS feed on?

I may look into it, though it isn't a top priority right now.

**Comment by 1fexd** [comment]
I'd like to read your blog posts via a local RSS reader, I don't want to embed the feed anywhere

**Comment by strazzere** [comment]
Got it.

Done --
https://strazzere.com/atom.xml
https://strazzere.com/rss2.xml

Seems like it works, assuming the reader can support the html type.
